name: Release

on:
  push:
    branches:
      - main

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
          run_install: |
            - recursive: true
              args: [--frozen-lockfile, --strict-peer-dependencies]

      - name: Create Release Pull Request
        uses: changesets/action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build
        # Ready to publish
        if: steps.changesets.outputs.hasChangesets == 'false'
        run: pnpm build

      - name: Publish
        # Ready to publish
        if: steps.changesets.outputs.hasChangesets == 'false'
        uses: actions/upload-artifact@v3
        with:
          name: scryfall-advanced-${{ steps.changesets.output.publishedPackages[0].version }}
          path: dist
