name: Release

on:
  push:
    branches:
      - main

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    outputs:
      skipPublish: ${{ steps.changesets.outputs.hasChangesets }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
          run_install: |
            - recursive: true
              args: [--frozen-lockfile, --strict-peer-dependencies]

      - name: Create Release Pull Request
        id: changesets
        uses: changesets/action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  publish:
    name: Publish
    needs: release
    if: needs.release.outputs.skipPublish == 'false'
    runs-on: ubuntu-latest
    steps:
      - name: Build
        run: pnpm build

      - name: Get Version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@v1.3.1

      - name: Upload extension artifacts
        uses: actions/upload-artifact@v3
        with:
          name: scryfall-advanced-v${{ steps.package-version.outputs.current-version }}
          path: dist

      - name: Publish
        uses: ncipollo/release-action@v1
        with:
          tag: v${{ steps.package-version.outputs.current-version }}
          artifacts: "scryfall-advanced-v${{ steps.package-version.outputs.current-version }}.zip"
          body: "Please refer to [CHANGELOG.md](https://github.com/rshigg/sf-advanced/blob/main/CHANGELOG.md) for details."
